# Generated by Django 3.1.4 on 2020-12-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_address_tag_toy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveObjectsManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
